steps:
  # Build the jar file
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-gcp-project/my-app:v1', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/my-gcp-project/my-app:v1']

  # Deploy the app to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'app',
      'deploy',
      '--image-url=gcr.io/my-gcp-project/my-app:v1',
      '--version=1',
      '--no-promote'
    ]
